kafkaBridgesReplicas: 3
kafkaConnectorsReplicas: 3
kafkaConnectsReplicas: 3
kafkaMirrorMaker2sReplicas: 3
kafkaMirrorMakersReplicas: 3
kafkaNodePoolsReplicas: 3
kafkaRebalancesReplicas: 3
kafkasReplicas: 3
kafkaTopicsReplicas: 3
kafkaUsersReplicas: 3
