apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${CLUSTER_NAME}
spec:
  kafka:
    version: ${KAFKA_VERSION}
    replicas: ${KAFKA_REPLICAS}
    template:
      pod:
        tolerations:
          - key: "app.stateful/component"
            operator: "Equal"
            value: "kafka-broker"
            effect: NoSchedule
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: "app.stateful/component"
                      operator: "In"
                      values: 
                        - "kafka-broker"
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: "topology.kubernetes.io/zone"
            whenUnsatisfiable: "DoNotSchedule"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: kafka
                strimzi.io/cluster: ${CLUSTER_NAME}
                strimzi.io/component-type: kafka
    resources:
      requests:
        memory: ${KAFKA_MEMORY_REQUEST}
        cpu: ${KAFKA_CPU_REQUEST}
      limits:
        memory: ${KAFKA_MEMORY_LIMIT}
        cpu: ${KAFKA_CPU_LIMIT}
    jvmOptions:
      -Xms: ${KAFKA_JVM_XMS}
      -Xmx: ${KAFKA_JVM_XMX}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: ${OFFSETS_TOPIC_REPLICATION_FACTOR}
      transaction.state.log.replication.factor: ${TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      transaction.state.log.min.isr: ${TRANSACTION_STATE_LOG_MIN_ISR}
      default.replication.factor: ${DEFAULT_REPLICATION_FACTOR}
      min.insync.replicas: ${MIN_INSYNC_REPLICAS}
      inter.broker.protocol.version: "${INTER_BROKER_PROTOCOL_VERSION}"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: ${KAFKA_STORAGE_SIZE}
          class: ${KAFKA_STORAGE_CLASS}
          deleteClaim: false
  zookeeper:
    template:
      pod:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: "app.stateful/component"
                      operator: "In"
                      values: 
                        - "zookeeper"
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: "topology.kubernetes.io/zone"
            whenUnsatisfiable: "DoNotSchedule"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: zookeeper
                strimzi.io/cluster: ${CLUSTER_NAME}
                strimzi.io/component-type: zookeeper
    replicas: ${ZOOKEEPER_REPLICAS}
    resources:
      requests:
        memory: ${ZOOKEEPER_MEMORY_REQUEST}
        cpu: ${ZOOKEEPER_CPU_REQUEST}
      limits:
        memory: ${ZOOKEEPER_MEMORY_LIMIT}
        cpu: ${ZOOKEEPER_CPU_LIMIT}
    jvmOptions:
      -Xms: ${ZOOKEEPER_JVM_XMS}
      -Xmx: ${ZOOKEEPER_JVM_XMX}
    storage:
      type: persistent-claim
      size: ${ZOOKEEPER_STORAGE_SIZE}
      class: ${ZOOKEEPER_STORAGE_CLASS}
      deleteClaim: false
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: ${TLS_SIDECAR_CPU_REQUEST}
          memory: ${TLS_SIDECAR_MEMORY_REQUEST}
        limits:
          cpu: ${TLS_SIDECAR_CPU_LIMIT}
          memory: ${TLS_SIDECAR_MEMORY_LIMIT}
    topicOperator:
      resources:
        requests:
          cpu: ${TOPIC_OPERATOR_CPU_REQUEST}
          memory: ${TOPIC_OPERATOR_MEMORY_REQUEST}
        limits:
          cpu: ${TOPIC_OPERATOR_CPU_LIMIT}
          memory: ${TOPIC_OPERATOR_MEMORY_LIMIT}
    userOperator:
      resources:
        requests:
          cpu: ${USER_OPERATOR_CPU_REQUEST}
          ephemeral-storage: ${USER_OPERATOR_EPHEMERAL_STORAGE_REQUEST}
          memory: ${USER_OPERATOR_MEMORY_REQUEST}
        limits:
          cpu: ${USER_OPERATOR_CPU_LIMIT}
          ephemeral-storage: ${USER_OPERATOR_EPHEMERAL_STORAGE_LIMIT}
          memory: ${USER_OPERATOR_MEMORY_LIMIT}
