

---
apiVersion: v1
kind: Namespace
metadata:
  name: olm-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer-sa
  namespace: olm-install
---
apiVersion: v1
kind: Pod
metadata:
  name: olm-installer
  namespace: olm-install
spec:
  serviceAccountName: olm-installer-sa
  containers:
  - name: olm-installer
    image: asure/olm:latest
    command: ["/bin/sh", "-c", "operator-sdk olm install && sleep 30"]
  restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: olm-install-role
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io", "apiextensions.k8s.io", "*"]
  resources: ["serviceaccounts", "clusterroles", "clusterrolebindings", "deployments", "customresourcedefinitions", "namespaces", "*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection", "escalate", "bind"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: olm-install-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: olm-install-role
subjects:
- kind: ServiceAccount
  name: olm-installer-sa
  namespace: olm-install
