apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-exporter-user
  labels:
    strimzi.io/cluster: strimzi-platform-my-cluster-dev
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations: 
          - Read
          - Describe
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations: 
          - Read
          - Describe