apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: strimzi-platform
  labels:
    app.kubernetes.io/name: kafka-exporter2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
      - name: exporter
        image: danielqsj/kafka-exporter:v1.7.0
        args:
        - --kafka.server=strimzi-platform-my-cluster-dev-kafka-bootstrap:9093
        - --kafka.version=3.6.2
        - --topic.filter=.*
        - --group.filter=.*
        - --log.level=info
        - --verbosity=0
        - --sasl.enabled
        - --sasl.mechanism=scram-sha512
        - --sasl.username=kafka-exporter-user
        - --sasl.password=MxrJTQHOCVzfZZbSkL6td07fW0xmPtcU
        env:
        - name: SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-exporter-user-secrets
              key: user.password
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9308
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 9308
          name: prometheus
