apiVersion: v1
kind: Pod
metadata:
  name: kafka-exporter
  namespace: strimzi-platform-dev
spec:
  containers:
  - name: exporter
    image: danielqsj/kafka-exporter:v1.7.0
    args:
      - --kafka.server=strimzi-platform-my-cluster-dev-kafka-bootstrap:9093
      - --kafka.version=3.6.2
      - --topic.filter=.*
      - --group.filter=.*
      - --log.level=info
      - --verbosity=2
      - --tls.enabled
      - --tls.ca-file=/etc/kafka/secrets/ca.crt
      - --tls.cert-file=/etc/kafka/secrets/user.crt
      - --tls.key-file=/etc/kafka/secrets/user.key

    ports:
    - containerPort: 9308
      name: prometheus
      protocol: TCP
    volumeMounts:
    - name: kafka-secrets
      mountPath: /etc/kafka/secrets
      readOnly: true
  volumes:
  - name: kafka-secrets
    secret:
      secretName: kafka-exporter-user-secrets
  restartPolicy: Always
