global:
  kafkaVersion: "3.0.0"
  kafkaReplicas: 3
  kafkaMemoryRequest: "2Gi"
  kafkaCpuRequest: "1"
  kafkaMemoryLimit: "4Gi"
  kafkaCpuLimit: "2"
  kafkaJvmXms: "2g"
  kafkaJvmXmx: "4g"
  kafkaListenersAuthenticationEnabled:
    plain: true
    tls: true
    external: true
  externalListenerTls: true
  externalDnsAnnotations:
    enabled: true
    dnsAnnotations:
      external-dns.alpha.kubernetes.io/hostname: "kafka.example.com"
  offsetsTopicReplicationFactor: 3
  transactionStateLogReplicationFactor: 3
  transactionStateLogMinIsr: 2
  defaultReplicationFactor: 3
  minInsyncReplicas: 2
  interBrokerProtocolVersion: "3.0"
  kafkaStorageSize: "10Gi"
  kafkaStorageClass: "standard"
  kafkaMetricsConfigName: "kafka-cluster-metrics-configmap"
  kafkaMetricsConfigKey: "kafka-metrics-config.yml"
  kafkaAuthorizationEnabled: true
  kafkaAuthorization:
    type: simple
    superUsers:
      - "CN=kafka-super-user"
  zookeeperReplicas: 3
  zookeeperMemoryRequest: "1Gi"
  zookeeperCpuRequest: "0.5"
  zookeeperMemoryLimit: "2Gi"
  zookeeperCpuLimit: "1"
  zookeeperJvmXms: "1g"
  zookeeperJvmXmx: "2g"
  zookeeperStorageSize: "5Gi"
  zookeeperStorageClass: "standard"
  zookeeperMetricsConfigName: "kafka-cluster-metrics-configmap"
  zookeeperMetricsConfigKey: "zookeeper-metrics-config.yml"
  tlsSidecarCpuRequest: "100m"
  tlsSidecarMemoryRequest: "128Mi"
  tlsSidecarCpuLimit: "200m"
  tlsSidecarMemoryLimit: "256Mi"
  topicOperatorCpuRequest: "100m"
  topicOperatorMemoryRequest: "128Mi"
  topicOperatorCpuLimit: "200m"
  topicOperatorMemoryLimit: "256Mi"
  userOperatorCpuRequest: "100m"
  userOperatorEphemeralStorageRequest: "1Gi"
  userOperatorMemoryRequest: "128Mi"
  userOperatorCpuLimit: "200m"
  userOperatorEphemeralStorageLimit: "2Gi"
  userOperatorMemoryLimit: "256Mi"



# global:

# ############################ KAFKA CONFIGURATION #############################################################################################################

#   # Nombre del clúster / Cluster name
#   clusterName: "my-cluster-dev"
  
#   # Versión de Kafka a utilizar / Kafka version to use
#   kafkaVersion: "3.7.1"  # Actualizado
  
#   # Número de réplicas para Kafka / Number of replicas for Kafka
#   kafkaReplicas: 1  # Actualizado
  


# #RECURSOS/RESOURCES
#   # Solicitudes de recursos para Kafka / Resource requests for Kafka
#   kafkaMemoryRequest: "2Gi"
#   kafkaCpuRequest: "500m"
  
#   # Límites de recursos para Kafka / Resource limits for Kafka
#   kafkaMemoryLimit: "2Gi"
#   kafkaCpuLimit: "1"
  
#   # Configuración de JVM para Kafka / JVM configuration for Kafka
#   kafkaJvmXms: "1024m"
#   kafkaJvmXmx: "1024m"
  


#  # Habilitar la autenticación en los listeners / Enable authentication on listeners
#   kafkaListenersAuthenticationEnabled:
#     plain: false
#     tls: true
#     external: true

#   # Habilitar TLS en el listener externo / Enable TLS on external listener
#   externalListenerTls: true
    
#   # Anotaciones DNS externas / External DNS annotations
#   externalDnsAnnotations:
#     enabled: false
#     dnsAnnotations:
#       external-dns.alpha.kubernetes.io/hostname: "kafka-bootstrap.mydomain.com."
#       external-dns.alpha.kubernetes.io/ttl: "60"



#   # Configuración de factores de replicación / Replication factor configuration
#   offsetsTopicReplicationFactor: 3  # Actualizado
#   transactionStateLogReplicationFactor: 3  # Actualizado
#   transactionStateLogMinIsr: 2  # Actualizado
#   defaultReplicationFactor: 3  # Actualizado
#   minInsyncReplicas: 2  # Actualizado
#   # Versión del protocolo entre brokers / Inter-broker protocol version
#   interBrokerProtocolVersion: "3.7"  # Actualizado
  
#   # Configuración de almacenamiento para Kafka / Storage configuration for Kafka
#   kafkaStorageSize: "30Gi"  # Actualizado
#   kafkaStorageClass: "standard"
  

#   # Configuración de métricas para Kafka / Metrics configuration for Kafka
#   kafkaMetricsConfigName: "kafka-cluster-metrics-configmap"  # Actualizado
#   kafkaMetricsConfigKey: "kafka-metrics-config.yml"
  
#   # Configuración de autorización para Kafka / Authorization configuration for Kafka
#   kafkaAuthorizationEnabled: true
#   kafkaAuthorization:
#     type: simple
#     superUsers:
#       - CN=my-user



# ############################ ZOOKEPER CONFIGURATION #############################################################################################################

# #RESOURCES
#   # Número de réplicas para Zookeeper / Number of replicas for Zookeeper
#   zookeeperReplicas: 1  # Actualizado
  
#   # Solicitudes de recursos para Zookeeper / Resource requests for Zookeeper
#   zookeeperMemoryRequest: "1Gi"
#   zookeeperCpuRequest: "200m"  
#   # Límites de recursos para Zookeeper / Resource limits for Zookeeper
#   zookeeperMemoryLimit: "1Gi"
#   zookeeperCpuLimit: "500m"
#   # Configuración de JVM para Zookeeper / JVM configuration for Zookeeper
#   zookeeperJvmXms: "512m"
#   zookeeperJvmXmx: "512m"

# #STORAGE
#   # Configuración de almacenamiento para Zookeeper / Storage configuration for Zookeeper
#   zookeeperStorageSize: "30Gi"  # Actualizado
#   zookeeperStorageClass: "standard"

# #METRICS  
#   # Configuración de métricas para Zookeeper / Metrics configuration for Zookeeper
#   zookeeperMetricsConfigName: "kafka-cluster-metrics-configmap"  # Actualizado
#   zookeeperMetricsConfigKey: "zookeeper-metrics-config.yml"


#   ############################ ENTITY OPERATOR CONFIGURATION #######################################################################################################

#   entityOperator:
#     tlsSidecar:
#       resources:
#         requests:
#           cpu: "50m"
#           memory: "64Mi"
#         limits:
#           cpu: "100m"
#           memory: "64Mi"
#     topicOperator:
#       resources:
#         requests:
#           cpu: "50m"
#           memory: "256Mi"
#         limits:
#           cpu: "100m"
#           memory: "256Mi"
#     userOperator:
#       resources:
#         requests:
#           cpu: "200m"
#           ephemeral-storage: "512Mi"
#           memory: "1Gi"
#         limits:
#           cpu: "200m"
#           ephemeral-storage: "512Mi"
#           memory: "1Gi"

#   ############################ POD MONITORING CONFIGURATION ########################################################################################################

#   # Configuración de PodMonitoring para Kafka y Zookeeper / PodMonitoring configuration for Kafka and Zookeeper
#   podMonitoringEnabled: true
#   kafkaExporterPodMonitoringName: "kafka-exporter"
#   kafkaExporterPodMonitoringPartOf: "google-cloud-managed-prometheus"
#   kafkaExporterPodMonitoringPort: "prometheus"
#   kafkaExporterPodMonitoringScheme: "http"
#   kafkaExporterPodMonitoringInterval: "30s"
#   kafkaExporterPodMonitoringPath: "/metrics"



    


#   # Habilitar autorización simple / Enable simple authorization
#   authorizationEnabled: true



