apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-client-tls
spec:
  secretName: kafka-client-tls-secret
  issuerRef:
    name: my-ca-issuer
    kind: Issuer
  commonName: kafka-client
