# templates/kafka-exporter.yaml
{{- if .Values.global.kafkaExporterEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: {{ .Values.global.kafkaExporterReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
      - name: exporter
        image: {{ .Values.global.kafkaExporterImage }}
        args:
        - --kafka.server={{ .Values.global.kafkaExporterKafkaServer }}
        ports:
        - containerPort: {{ .Values.global.kafkaExporterContainerPort }}
          name: prometheus
{{- end }}
---
