# templates/kafka-exporter.yaml
{{- if .Values.global.kafkaExporterEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: {{ .Values.global.kafkaExporterReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
      - name: exporter
        image: {{ .Values.global.kafkaExporterImage }}
        args:
        - --kafka.server={{ .Values.global.kafkaExporterKafkaServer }}
        - --kafka.version=3.6.2
        - --topic.filter=my-topic
        - --group.filter=.*
        - --log.level=info
        - --verbosity=0
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9308
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.global.kafkaExporterContainerPort }}
          name: prometheus
{{- end }}
---
