{{- if .Values.global.kafkaExporterEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: {{ .Values.global.kafkaExporterReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
      annotations:
        {{- if .Values.global.prometheusManagedServiceEnabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.global.kafkaExporterContainerPort }}"
        {{- end }}
    spec:
      containers:
        - name: exporter
          image: {{ .Values.global.kafkaExporterImage }}
          args:
            - --kafka.server={{ .Values.global.kafkaExporterKafkaServer }}
          ports:
            - containerPort: {{ .Values.global.kafkaExporterContainerPort }}
              name: prometheus
{{- end }}
---
{{- if and .Values.global.kafkaExporterEnabled .Values.global.prometheusManagedServiceEnabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
    - port: prometheus
      scheme: {{ .Values.global.kafkaExporterPrometheusScheme }}
      interval: {{ .Values.global.kafkaExporterPrometheusInterval }}
      path: {{ .Values.global.kafkaExporterPrometheusPath }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
{{- end }}
